export const PROMPTS = [
  "Something you would hate to hear from your dentist",
  "A food that is annoying to eat in the car",
  "A bad animal to bring to a wedding",
  "Something that should never crunch",
  "A smell that can ruin your day",
  "A bad thing to forget on vacation",
  "Something people pretend to enjoy",
  "An animal that feels rude",
  "A terrible flavor for toothpaste",
  "Something you should not say on a first date",
  "A bad thing to hear right before takeoff",
  "Something that always disappears in a house",
  "A chore everyone procrastinates",
  "A food you regret ordering when it arrives",
  "Something that is worse when it is sticky",
  "A place where you should whisper",
  "A thing you should never microwave",
  "A word that sounds funny when yelled",
  "Something that should come with a warning label",
  "An item that is always harder to open than it should be",
  "A sound that means trouble",
  "A snack that is impossible to eat quietly",
  "Something you should not drop in public",
  "A bad name for a pet fish",
  "A thing that should not be scented",
  "A reason to immediately leave a restaurant",
  "A bad thing to run out of during a party",
  "Something people only clean when guests are coming",
  "A food that is risky to wear while dressed up",
  "A terrible song choice for a funeral",
  "A bad thing to hear from your mechanic",
  "Something that always takes longer than expected",
  "A place where flip-flops are a bad idea",
  "A bad gift for someone you barely know",
  "A thing that should never be glittery",
  "Something you should not say in a job interview",
  "A condiment people have strong opinions about",
  "A smell that instantly makes a room suspicious",
  "A thing people lose in couch cushions",
  "A bad mascot for a hospital",
  "A place where your phone should be on silent",
  "A bad time to get the hiccups",
  "Something that is difficult to explain to a child",
  "A food that divides a friend group",
  "A bad thing to hear on a roller coaster",
  "Something that should not be crunchy",
  "A bad surprise in your shoe",
  "An object that is always colder than expected",
  "A bad place to discover a leak",
  "Something that should never be in a smoothie",
  "A thing that feels illegal but is not",
  "A bad animal to find in your bathroom",
  "Something that should not be a pizza topping",
  "A bad thing to yell in a library",
  "A reason to cancel plans immediately",
  "A thing that gets worse the more expensive it is",
  "A bad excuse for being late",
  "A thing you should not bring to a beach",
  "Something that should never be reheated",
  "A bad thing to hear from your barber",
  "A place where you should not take a selfie",
  "A thing everyone pretends to understand",
  "A bad costume for a kindergarten teacher",
  "Something that should not be glowing",
  "A bad smell for a candle",
  "A thing people clap for even when confused",
  "A terrible prize to win at a carnival",
  "A thing you should never say to your boss",
  "A food that is mostly an excuse for sauce",
  "A bad thing to spill on a white shirt",
  "A place where a joke can go very wrong",
  "Something that feels longer than 10 minutes",
  "A bad thing to hear during a haircut",
  "A movie snack that is too loud",
  "A thing that always causes a group debate",
  "A bad thing to forget before camping",
  "Something that should not be battery-powered",
  "A bad thing to hear from your pilot",
  "A food that should never be room temperature",
  "A bad surprise in a hotel room",
  "Something you should not say at a wedding toast",
  "A thing people overpack for",
  "A bad item to step on barefoot",
  "A place where singing is a terrible idea",
  "Something that should not be slippery",
  "A bad thing to hear from your doctor",
  "A food that is impossible to eat politely",
  "Something people always forget at the grocery store",
  "A bad name for a roller coaster",
  "A thing that should never be personalized",
  "A reason to mute yourself on a video call",
  "A bad thing to hear from your plumber",
  "A smell that should never come from your fridge",
  "Something that is scarier at night",
  "A bad thing to hear from your babysitter",
  "A thing that should not be served warm",
  "A place where you should not test your luck",
  "A bad thing to hear right before photos are taken",
  "Something you should never put in your pocket",
  "A bad opening line for a speech"
] as const;
